# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Yale Data Science
tagline:          'An Undergraduate Organization'
description:      'An Undergraduate Organization'
url:              http://yaledatascience.github.io/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
  github:           https://github.com/YaleDataScience/
  repo:           https://github.com/YaleDataScience/
